### ISSUE TITLE
Question: Is it possible to use PostgreSQL?

### ISSUE THREAD

**Issue by tcassaert** [viktorstrate/photoview#113]
This project looks great!

Currently I'm mainly using PostgreSQL for all my self hosted apps. Is it possible to use it for this as well? Or is MariaDB a hard requirement for now?

Thanks in advance!

**Comment by viktorstrate** [comment]
Hi @tcassaert, thank you for your interest in the projet.

MariaDB (or MySQL) is currently the only supported databases, as it would require some effort to add, test and maintain more database systems, as they all differ a little in syntax and capabilities.

I don't think PostgreSQL support will be added because of that.

If you, or someone else thinks otherwise, please comment your believes why and I will reopen the thread.

**Comment by tcassaert** [comment]
Thanks for your quick reply. I totally understand that this would give extra maintenance.
