### ISSUE TITLE
Running with armhf (v7) 

### ISSUE THREAD

**Issue by BkSouX** [viktorstrate/photoview#23]
Hi, 

First, great project idea ! I was looking for that kind of app for my personal server and my photos.

I'm trying to run it with an armv7 processor.

I have done some specific modifications in the dockercompose:

 - the mariadb version is not compatible and I already have a Mariadb on my server so I removed the mariadb part and add the IP of the database
```
$ mariadb --version
mariadb  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnueabihf (armv8l) using readline 5.2
```
 -  I had to modify the go build to build into arm v7.
```
RUN CGO_ENABLED=0 GOOS=linux GOARM=7 GOARCH=arm go build -o photoview .
```

It runs, connects to Mariadb (I suppose) but after I have an error : 

```
CREATE TABLE IF NOT EXISTS photo_url (
  url_id int NOT NULL AUTO_INCREMENT,
  photo_id int NOT NULL,
  photo_name varchar(512) NOT NULL,
  width int NOT NULL,
  height int NOT NULL,
  purpose varchar(64) NOT NULL,
  content_type varchar(64) NOT NULL,

  PRIMARY KEY (url_id),
  FOREIGN KEY (photo_id) REFERENCES photo(photo_id) ON DELETE CASCADE
); (details: Error 1071: Specified key was too long; max key length is 3072 bytes)
2020/04/13 10:49:49 No .env file found
2020/04/13 10:49:49 Connecting to database: username:password@tcp(192.168.1.38)/photoview?multiStatements=true&parseTime=true
2020/04/13 10:49:49 Could not migrate database: Dirty database version 2. Fix and force version.
```

The database was empty.

Maybe you'll have an idea !
I continue to look.

**Comment by stz184** [comment]
I have the same issue using MySQL 5.7.30 on Ubuntu 18.04 instead of MariaDB.
According to the official [MariaDB documentation](https://mariadb.com/kb/en/innodb-limitations/), the maximum key length is 3072B (the same as in MySQL) 
I don't really get it why the hell the migration is successful using docker and mariadb image but it fails on MySQL. It should throw an error always because the max key length is exceeded no matter MySQL or MariaDB is used.

**Comment by viktorstrate** [comment]
> Actually, the problem is in the database design, not in the database engine.

@stz184 can you point out what in the current database design / migrations that causes the maximum key length to be exceeded? And how could we change it to resolve the problem?

**Comment by stz184** [comment]
> > Actually, the problem is in the database design, not in the database engine.
> 
> @stz184 can you point out what in the current database design / migrations that causes the maximum key length to be exceeded? And how could we change it to resolve the problem?

You want to use utf8mb4 character set which is a 4-Byte UTF-8 unicode encoding. That means that your photo.path column defined as VARCHAR(1024) actually can store up to 4096 bytes which is much bigger than the max key length (3072 bytes for bot MariaDB and MySQL).

According to the official [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-conversion.a):

>  InnoDB has a maximum index length of 767 bytes for tables that use COMPACT or REDUNDANT row format, so for utf8mb3 or utf8mb4 columns, you can index a maximum of 255 or 191 characters, respectively. If you currently have utf8mb3 columns with indexes longer than 191 characters, you must index a smaller number of characters. 

That's not absolutely correct, because If innodb_large_prefix is enabled, the index key prefix limit is increased to 3072 bytes. Anyway, in both cases, you can't have an index on a varchar column with size 1024. (reference: https://dev.mysql.com/doc/refman/5.7/en/innodb-limits.html)

So, what is the workaround? We can have a unique index on the path hash instead of the path itself. We just need to add an additional column, let's say `path_hash` and apply a unique constraint to it.

if you want, I can do that. 

What I still can't wrap my head around is why this limit is not enforced when I run photoview using docker and latest MariaDB image.

**Comment by viktorstrate** [comment]
@stz184 Thank you for the explaination, I didn't know that indexes are generated for `unique` columns, all though it totally makes sense.

I like your suggested solution. I would appreciate if you send a pull request 😊
Maybe the length of the album.path should also be updated to 1024 also with a hashed `unique` index.

**Comment by viktorstrate** [comment]
Now where #53 have been merged, the database problems should have been solved.
@BkSouX, I don't have an ARM device to test it though. Would you mind testing it again?

Also what is needed in order to build and distribute the docker image for ARM aswell?

**Comment by viktorstrate** [comment]
The photoview docker image is now published as an arm version as well 🎉🚀
