### ISSUE TITLE
Installation on Podman 

### ISSUE THREAD

**Issue by Ke1i** [viktorstrate/photoview#37]
As someone who ditched piwigo, I was excited to checkout photoview. But I'm on podman and not docker so docker compose won't work for me. I figured out the basics from the provided 'docker-compose.example.yml' and tried the command below:

```
sudo podman run -dt --pod fox --name=photoview -p 8000:80 -e MYSQL_URL='root:myrootpassword@tcp(127.0.0.1)'/photoview -e API_LISTEN_IP=127.0.0.1 -e API_LISTEN_PORT=8000 -e PHOTO_CACHE=/app/cache -e SERVE_UI=1 -e PUBLIC_ENDPOINT=http://127.0.0.1:8000/ -v /public/Photos/cache:/app/cache:z -v /public/Photos:/photos:z --net=host docker.io/photoview
```
Unfortunately I get this error when pulling the image:

```
Trying to pull docker.io/photoview...
  denied: requested access to the resource is denied
Error: error pulling image "docker.io/photoview": unable to pull docker.io/photoview: unable to pull image: Error initializing source docker://photoview:latest: Error reading manifest latest in docker.io/library/photoview: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```
Do I need a docker account to pull the image?
I tried searching the image manually in dockerhub but the only listed image that resembles what I'm looking for is 'r1chjames/photoview'.
I downloaded it just to test and I get the error below:

```
fox@ke1i ~]$ sudo podman logs photoview
2020/04/29 11:03:39 No .env file found
2020/04/29 11:03:39 Connecting to database: root:*******@tcp(127.0.0.1)/photoview?multiStatements=true&parseTime=true
2020/04/29 11:03:39 Database is up to date
2020/04/29 11:03:39 Photoview API endpoint listening at http://127.0.0.1:8000/api
2020/04/29 11:03:39 Photoview API public endpoint ready at http://ke1i.duckdns.org:8000/api
2020/04/29 11:03:39 Photoview UI public endpoint ready at http://ke1i.duckdns.org:8000/
2020/04/29 11:03:54 GET 304 ke1i.local:8000/ 5.90317ms unauthenticated
```
I get a blank page when I visit the public endpoint. So I know podman isn't the issue. 

Additional  information:

I already have a mariadb instance running (linuxserver.io one) and I've created a database named 'photoview' in it.

**Comment by viktorstrate** [comment]
You cannot pull photoview from `docker.io/photoview` because it doesn't exist.
I haven't published the docker image to dockerhub, but I see that r1chjames has posted an unofficial image.

But it seems like photoview starts up and connects to the database correctly.
The problem might be bacause you are connecting to it from another domain than you have specified from the PUBLIC_ENDPOINT env variable.
It looks like photoview is expecting connections from `http://ke1i.duckdns.org:8000/`, but you connect to it from `ke1i.local:8000`.

It is important that PUBLIC_ENDPOINT match the url that you visit photoview from in the browser.

Are there any errors in the _developer console_, or failed _network requests in the _network tab_, when visiting the blank page from the browser (Press F12 to show)?

**Comment by Ke1i** [comment]
That's what I thought after reading through some of the issues but it didn't help. If I set and visit the url exactly like it should be in the PUBLIC_ENDPOINT variable, it's the same. I get a blank page. But this time, the errors aren't logged.
If I visit the API endpoint (http://ke1i.duckdns.org:8000/api/) I get a 'photoview api point' text on the browser. 
Log output:

```
[fox@ke1i ~]$ sudo podman logs photoview
2020/04/29 13:54:34 No .env file found
2020/04/29 13:54:34 Connecting to database: root:adminis321@tcp(127.0.0.1)/photoview?multiStatements=true&parseTime=true
2020/04/29 13:54:34 Database is up to date
2020/04/29 13:54:34 Photoview API endpoint listening at http://127.0.0.1:8000/api
2020/04/29 13:54:34 Photoview API public endpoint ready at http://ke1i.duckdns.org:8000/api
2020/04/29 13:54:34 Photoview UI public endpoint ready at http://ke1i.duckdns.org:8000/
2020/04/29 13:55:00 GET 200 ke1i.local:8000/api/ 317.93µs unauthenticated
2020/04/29 13:55:45 GET 200 ke1i.duckdns.org:8000/api/ 253.383µs unauthenticated
2020/04/29 13:57:35 GET 200 ke1i.local:8000/api/ 202.53µs unauthenticated
2020/04/29 13:58:20 GET 301 ke1i.duckdns.org:8000/ui/index.html 2.35263ms unauthenticated
2020/04/29 13:58:20 GET 200 ke1i.duckdns.org:8000/ui/ 2.626666ms unauthenticated
```
As you can see from the above, errors for accessing the PUBLIC_ENDPOINT url exactly as it is aren't logged. Unless I start digging into the folders.

Here's the web console error:
`
Loading failed for the <script> with source “https://photos.r1chjames.co.uk/src.23ab0661.js”.`

Digging further:

```
sudo podman exec -it photoview cat /ui/index.html

<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="https://photos.r1chjames.co.uk/src.d4804212.css"></head><body> <div id="root"></div> <script src="https://photos.r1chjames.co.uk/src.23ab0661.js"></script> </body></html>
```
Looks like the guy injected something.

Anyway, where's that .env supposed to be? I created one and tried binding it to '/ui/.env' but that didn't help. I still got the 'no .env file found' error in the logs.

**Comment by viktorstrate** [comment]
The .env is supposed to be there, it is just a message. That file is only being used while developing or if it is being hosted directly on the system outside of a container.

Okay I think there might be two problems

First, the javascript for the website is not being loaded properly, hence the <script> error.
In the web console does it say anything about why it failed to load? Either a `404 not found` or somthing about `CORS`?

The other thing is a bit more tricky. Currently, in the docker-compose example config, the photoview container is being built from scratch instead of being downloaded from dockerhub, as I haven't made a public image yet. And while building the `API_ENDPOINT` variable is being used to compile the url of the api directly into the static javascript, and if that url is wrong, the website cannot communicate with the api.

This could probably be fixed by changing how the ui connects to the api slightly. I might look into that some time.

You could probably also build the image yourself and use that with podman.
I have never used podman but somthing like this:

First clone the repository, then build the image, with the API_ENDPOINT build arg

    $ podman build --build-arg API_ENDPOINT=http://ke1i.duckdns.org:8000/api/ -t my-photoview ./photoview/Dockerfile

If it works you should be able to start photoview with your own image

    $ podman run [ ... ] my-photoview

**Comment by Ke1i** [comment]
I was testing without an internet connection so I retested and it looks like an authentication problem. 

```
The resource from “https://accounts.google.com/signin/oauth?client_id=936728070…james.co.uk/src.d4804212.css&o2v=2&as=Ufyg48pcjhzU-qLO4oA6rw” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
ke1i.duckdns.org:8000
The resource from “https://accounts.google.com/signin/oauth?client_id=936728070…hjames.co.uk/src.23ab0661.js&o2v=2&as=JhbFC0UaD0-0A5Z1YmsjQQ” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
ke1i.duckdns.org:8000
Loading failed for the <script> with source “https://photos.r1chjames.co.uk/src.23ab0661.js”. ke1i.duckdns.org:8000:1:1
```
I'll have to look into building the image as you suggested.

**Comment by viktorstrate** [comment]
Okay, I don't know where the google sign ins come from though? :)

**Comment by Ke1i** [comment]
I've decided to build it.. after a couple of tries, this is what seems to work:

`
sudo podman build . -t photoview --build-arg=API_ENDPOINT=http://ke1i.duckdns.org:8000/api/`

Fingers crossed ;)

**Comment by Ke1i** [comment]
Finally!
I was able to make it work :)

The build failed because I was missing some arguments. So for anyone reading this, to successfully build the image on podman, run:

`sudo podman build . -t my-photoview --build-arg=API_ENDPOINT=http://<your.domain>:8000/api/ --build-arg=UI_PUBLIC_URL=http://<your.domain>:8000/`

It should build successfully. 
I encountered some errors but the image did build.

Then run the local container using:

`sudo podman run -dt --name=photoview -p 8000:80 -e MYSQL_URL='root:<yourrootpassword>@tcp(127.0.0.1)'/photoview -e API_LISTEN_IP=127.0.0.1 -e API_LISTEN_PORT=8000 -e PHOTO_CACHE=/app/cache -e SERVE_UI=1 -e PUBLIC_ENDPOINT=http://<your.domain>:8000/ -v /public/Photos/cache:/app/cache:z -v /public/Photos:/photos:z --net=host localhost/my-photoview`

It should work.

**Comment by viktorstrate** [comment]
Awesome! Thanks for sharing your solution 👍

**Comment by Ke1i** [comment]
..and thanks you for the beautiful gallery :)
