### ISSUE TITLE
Moved or deleted photos are not properly deleted when rescanning

### ISSUE THREAD

**Issue by viktorstrate** [viktorstrate/photoview#56]
When a photo is deleted or moved, it is not removed from the database when rescanning.

**Comment by stz184** [comment]
I am on it.

**Comment by viktorstrate** [comment]
Awesome, thank you!

**Comment by ced455** [comment]
Hello I am reopening this issue,

I deleted a few thousand pictures recently and I still could see the thumbnails, I then deleted all of them, performed a new scan, and now the pictures are still there but blurry, same for the faces.
I obviously ran a full scan.

I am running it on docker V2.3.12 , and mariadb latest

![image](https://user-images.githubusercontent.com/26870023/163437401-a01f669e-a359-4254-b758-4e8307d2af90.png)
![image](https://user-images.githubusercontent.com/26870023/163437512-2f0231ee-0d95-4450-85ea-1ebd7272daec.png)


I would like to avoid deleting the database since it took me quite some time to label and merge all my faces.  
Is there a way to trigger a scan that detect deleted images ?

thank you.

**Comment by DaCHack** [comment]
Same here!
@viktorstrate : I see the project is a little stale recently. I would not expect a fix, but maybe just a hint for a workaround would be appreciated.

It took me 10 days to scan the media library. I now have a couple of images where the dates in EXIF data where in the future and needed to be corrected. I temporarily moved the affected subfolders out of the scan hierarchy and did a rescan. But the images remain available with their blurred and thumbnail versions. I do want to avoid nuking the entire cache and database and re-do the whole 10 days :(

**Comment by DaCHack** [comment]
#682 Same issue

**Comment by DaCHack** [comment]
FYI: It seems you can workaround this issue by
1) removing the affected subfolders from all users except for one
2) moving the files out of the scan tree
3) scan the tree for one that one remaining user
4) move the files back again
5) scan the tree for that one user again
6) add the tree to other users again (and rescan if needed)

Very cumbersome, but better than nuking the database...

**Comment by DaCHack** [comment]
Bad news... A full rescan of all users this night made the deleted pictures appear again with the wrong EXIF data for all users :(

Any ideas how to manually edit the extracted data in the database without breaking anything?

**Comment by DaCHack** [comment]
For any other users with the same issue and my own reference I will share my workaround here:

This includes editing the fields in the media and media_exif tables in the database directly so I hope this was correct and does not cause any inconsistencies. Please let me know if this could be the case:

### (1) Whole folder with date consistently 20 years in the future:
```
UPDATE media SET date_shot=DATE_SUB(date_shot, INTERVAL 20 YEAR) WHERE path LIKE '%PART_OF_FOLDER_NAME_HERE%'
SELECT GROUP_CONCAT(exif_id) FROM media WHERE path LIKE '%PART_OF_FOLDER_NAME_HERE%';
UPDATE media_exif SET date_shot=DATE_SUB(date_shot, INTERVAL 20 YEAR) WHERE id IN (COPY LIST OF PREVIOUS COMMAND HERE);
```

### (2) Specific images affected (eg. EXIF date showing Jan 01 4501 to be corrected to Oct 30 2017)
```
SELECT GROUP_CONCAT(exif_id) FROM media WHERE (path LIKE '%PART_OF_FOLDER_NAME_HERE%' AND date_shot LIKE '%4501-01-01%');
UPDATE media SET date_shot="2017-10-30 00:00:00.000" WHERE (path LIKE '%PART_OF_FOLDER_NAME_HERE%' AND date_shot LIKE '%4501-01-01%');
UPDATE media_exif SET date_shot="2017-10-30 00:00:00.000" WHERE id IN (COPY LIST OF PREVIOUS COMMAND HERE);
```
