### ISSUE TITLE
Invalid root path for pictures?

### ISSUE THREAD

**Issue by Nobrac** [viktorstrate/photoview#66]
Hey there.

Thank you very much for this project but I have the following problem.

Always when I want to change the "Photo path" in the Web-GUI I get the following error:
![servererror](https://user-images.githubusercontent.com/22682116/90319454-a48ba800-df38-11ea-9cb3-8e30c42f25d5.JPG)

I don't have much experience with Docker. Probably a small mistake made by me.

I would like to change my photo path to: /etc/photos

What do I need to change?

Thank you for your help.

**Comment by viktorstrate** [comment]
Hi Nobrac

This error occures because the given path doesn't exist on the file system (inside the docker container).
For the docker container to access your photos, you have to [bind](https://docs.docker.com/storage/bind-mounts/) your directory from the host to inside the container.
This is done from the `docker-compose.yml` file. To bind `/etc/photos/´ you could add the following volume to the compose config file:

```yml
services:
  photoview:
    volumes:
      - /etc/photos:/photos:ro
```

This means that the `/etc/photos` directory on the host, will be mapped to `/photos` in the container. The `:ro` at the end, means that the mount will be read-only.

Now, because the photos directory is mapped to `/photos` inside the container, you would have to put the same as the root path on the web-gui.
I hope that makes sense 😊

**Comment by Nobrac** [comment]
Hey.

That worked. Thank you very much for the good explanation.

/solved

**Comment by viktorstrate** [comment]
Awesome 🎉
