### ISSUE TITLE
Container crashes trying to run db migration

### ISSUE THREAD

**Issue by ThisIsQasim** [viktorstrate/photoview#73]
Updated to the latest image from an old image with a working setup. Now the container crashes while trying to run db migration.

```
2020/08/28 09:11:05 Connecting to database: user:password@tcp(mysql-host)/photoview?multiStatements=true&parseTime=true
photoview_1  | 2020/08/28 09:11:05 Could not migrate database: file does not exist
photoview_1  | panic: Could not migrate database: file does not exist
photoview_1  | 
photoview_1  | 
photoview_1  | goroutine 1 [running]:
photoview_1  | log.Panicf(0xa5ccca, 0x1f, 0xc0002557e8, 0x1, 0x1)
photoview_1  |  /usr/local/go/src/log/log.go:358 +0xc0
photoview_1  | main.main()
photoview_1  |  /app/server.go:41 +0x1a5
```

**Comment by viktorstrate** [comment]
The initial release had breaking changes, because the software didn't have a proper versioning system beforehand, there wasn't any good way to update without breaking backwards compatibility.

The best option would be to wipe the database, and configure photoview again. This way you can get future updates.
Now with a proper versioning system, you will always be able to update with automatic migrations, as long as you stay on version `1.x.x`, by using the docker image `viktorstrate/photoview:1`

I am sorry for the inconvenience this might introduce, I made a lot of changes to the database to ensure as few changes to the database as possible in the future.

**Comment by ThisIsQasim** [comment]
No worries. I deleted the existing database and the app started working. Thank you for the great piece of software!
